# Stage 1: Dependencies
FROM node:20-slim AS deps
WORKDIR /app

# Install dependencies based on environment
ARG BUILD=development
COPY package.json yarn.lock* package-lock.json* ./

RUN if [ "$BUILD" = "production" ]; then \
    npm install --production --legacy-peer-deps && npm cache clean --force; \
    else \
    npm install --legacy-peer-deps --ignore-scripts; \
    fi


FROM deps AS development
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
